apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foxapp-argo-appliication
  namespace: argocd
spec: 
  project: default

  source:
    repoUrl: https://github.com/Aleqxan/Argocd-config.git
    targetRevision: HEAD
    path: Dev
  destination:
    server: https://kubernetes.default.svc
    namespace: foxapp

  syncpolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true